version: 2
jobs:
  build:
    working_directory: ~/emoji
    machine: true
    steps:
     - checkout
     - run:
         command: |
           sudo apt update
           sudo apt install -y snapd
           sudo snap install snapcraft --edge --classic
           /snap/bin/snapcraft
     - deploy:
         name: Push Master to Snap Store
         command: |
           openssl aes-256-cbc -d -in .snapcraft/snapcraft.encrypted -out .snapcraft/snapcraft.cfg -k $KEY
           /snap/bin/snapcraft push *.snap --channel edge
